[versions]
kotlin = "1.8.0"
junit = "5.9.1"

[libraries]
commons-csv = { module = "org.apache.commons:commons-csv", version = "1.8" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }

[plugins]
kotlin-jvm = {id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin"}
